### ISSUE TITLE
ETags, If-Match

### ISSUE THREAD

**Issue by andreineculau** [webmachine/webmachine#103]
For the long story, please read https://groups.google.com/d/topic/api-craft/OmWtAPYLd6w/discussion

tl;dr
there is no way to know if generate_etag is called for the purpose of validating the If-(None-)Match header, or for actually generating an ETag for the response.
And while this might not be obvious to the untrained eye, the ETag that you send in as a precondition does not have to be calculated based on the same media-type as the response.

Wdyt?

**Comment by andreineculau** [comment]
http://tools.ietf.org/html/draft-ietf-httpbis-p4-conditional-21 says

> If any of the entity-tags listed in the If-Match field value match (as per Section 2.3.2) the entity-tag of the selected representation for the target resource...

and

> We use the term "selected representation" to refer to the current representation of the target resource that would have been selected in a successful response if the same request had used the method GET and had excluded all of the conditional request header fields. 

which leaves it to: "If-Match" ETags are linked to the media-type negotiated based "Accept".

Makes for a brittle coupling (exemplified in the discussion in gGroups), but that's a spec issue and not a webmachine-is-not-following-the-spec issue. _sigh_

**Comment by seancribbs** [comment]
@andreineculau One thing that could be ported from the Ruby version of webmachine is direct support for ["weak" ETags](seancribbs/webmachine-ruby#59), which can help solve validation/matching problems although they aren't as cache-friendly.
