### ISSUE TITLE
media_type_to_detail/1 strips quoted media param values

### ISSUE THREAD

**Issue by jrwest** [webmachine/webmachine#111]
The change in https://github.com/basho/webmachine/commit/ac48b09c3d628730620526a365c1dcae79e76b9a to address extra whitespace also had the side-effect of stripping quotes from media range params (https://github.com/basho/mochiweb/blob/master/src/mochiweb_util.erl#L378). Since master improperly handles media range params this hasn't been an issue before. While trying to merge #112, which address the media param issues, however, @kellymclaughlin and I noticed that the quoted strings are lost in the round-trip between `media_type_to_detail/1` and `format_content_type/1`.

post-ac48b09c:

```
1> MT = "application/vnd.custom;version=\"abc\"".
"application/vnd.custom;version=\"abc\""
2> webmachine_util:media_type_to_detail(MT). 
{"application/vnd.custom",[{"version","abc"}]}
```

pre-ac48b09c:

```
1> MT = "application/vnd.custom;version=\"abc\"".
"application/vnd.custom;version=\"abc\""
2> webmachine_util:media_type_to_detail(MT). 
{"application/vnd.custom",[{"version","\"abc\""}]}
```

**Comment by kellymclaughlin** [comment]
@vinoski Any thoughts on this? It looks like a mochiweb bug to me, but wanted to get your thoughts.

**Comment by vinoski** [comment]
The `mochiweb_util:parse_header/1` fun is definitely stripping the quotes, but I don't think it's a bug there. The comment in the mochiweb source above that function says it parses "a Content-Type like header" and if you look at RFC 2046 there's a multipart example:

```
Content-Type: multipart/mixed; boundary="gc0pJq0M:08jU534c0p"
```

where the quotes around the boundary parameter value are definitely not treated as part of the value, and are instead stripped, so I'm sure that's why mochiweb implements it the way it does.

Do we know for sure that quotes are valid parts of parameter values for media types? I tried digging through RFCs but came up empty. If they're really allowed, then we'll have to move away from using the mochiweb function for this case and back to the old webmachine code.

**Comment by kellymclaughlin** [comment]
I was looking at sec 3 of [rfc 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html). In particular this from section 3.7:

> HTTP uses Internet Media Types [17] in the Content-Type (section 14.17) and Accept (section 14.1) header fields in >order to provide open and extensible data typing and type negotiation.
> 
> ```
>   media-type     = type "/" subtype *( ";" parameter )
>   type           = token
>   subtype        = token
> ```
> 
> Parameters MAY follow the type/subtype in the form of attribute/value pairs (as defined in section 3.6).

And then the relevant text from 3.6:

> Parameters are in the form of attribute/value pairs.
> 
> ```
>   parameter               = attribute "=" value
>   attribute               = token
>   value                   = token | quoted-string
> ```

**Comment by vinoski** [comment]
Good info. And following on from that, if you look at the [HTTPbis](http://tools.ietf.org/wg/httpbis/) work to clarify HTTP 1.1, you'll find this in [section 3.1.1.1](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#section-3.1.1.1), which is the update to the RFC 2616 section you quoted:

```
A parameter value that matches the token production can be transmitted as either a token
or within a quoted-string.  The quoted and unquoted values are equivalent.
```

I think this pretty clearly states that quotes are not considered part of the value, so I think that means sticking with the mochiweb function is fine.

**Comment by kellymclaughlin** [comment]
Ah perfect, so we can close this issue and just modify our test. Thanks for the input, Steve!

**Comment by jrwest** [comment]
sweet. thanks guys. closing this issue.
