### ISSUE TITLE
content_types_accepted

### ISSUE THREAD

**Issue by andreineculau** [webmachine/webmachine#122]
This is described in the wiki as

> This is used similarly to content_types_provided, except that it is for incoming resource representations – for example, PUT requests. Handler functions usually want to use wrq:req_body(ReqData) to access the incoming request body.

along with this extra info

> POST-processing function named as a Handler by content_types_accepted

If one runs the code though, reality is different:
`content_types_accepted` is only used by `accept_helper`, which is called only when
1) the request is a POST and `post_is_create` is true
2) the request is a PUT and `is_conflict` is false

Meaning that all POST requests are skipping the handlers. By the look of the code, webmachine assumes that the resource should call the request-content-type handler inside the `process_post` callback ?

IMO either the documentation should be updated,
either webmachine should be calling the request-content-type handler before calling `process_post`.
Can anyone concur?

**Comment by sebastian** [comment]
Yes, this behaviour puzzles me too.
I would also expect the handlers provided in `content_types_accepted` to be invoked, even when `post_is_create` returns false.

**Comment by robertoaloi** [comment]
Bump?

**Comment by nickretallack** [comment]
Wait, seriously?  It doesn't read the PUT payload until is_conflict has already returned false?  That sounds pretty backwards to me.

**Comment by tmcgilchrist** [comment]
Bump?

**Comment by beerriot** [comment]
I have updated https://github.com/webmachine/webmachine/wiki/Resource-Functions to be more explicit about `content_types_accepted` only applying to POST when `post_is_create` is `true`.
