### ISSUE TITLE
known_content_type

### ISSUE THREAD

**Issue by andreineculau** [webmachine/webmachine#123]
`known_content_type` is supposed to return true/false and thus trigger a 415 response code, based on the request-content-type.

What is the idea behind this callback, given that there is already a `content_types_accepted` callback?

Is it wrong to say that the decision b5 can just take a decision by doing `get_content_types_accepted` and matching that with the request-content-type ?

Currently, if you don't implement the `known_content_type` callback, a POST/PUT could go all sort of things like reading the resource, etc only to find out that the request was sent with an unknown content type.

**Comment by beerriot** [comment]
As discussed in #122, `content_types_accepted` does not apply to POST requests. But, `known_content_type` does, and it would allow you to get an appropriate response sent if your `process_post` was not prepared to handle what was sent.
