### ISSUE TITLE
The latest webmachine does not work with Riak master branch

### ISSUE THREAD

**Issue by jj1bdx** [webmachine/webmachine#129]
The following two commits had to be backed off to run Riak of branch `master` at
https://github.com/basho/riak/commit/2435463113ff2c41c49f35c80a221cd4581ca62a

Failed commits:
https://github.com/basho/webmachine/commit/b2ff665799a5527c904df6aaf5030eb2be24e24b
https://github.com/basho/webmachine/commit/75203f1355064d3ebf3d3ca1d5a13d529933ed5f

See https://github.com/basho/riak/issues/280 for the details.

**Comment by seancribbs** [comment]
This has been resolved by #128

**Comment by jj1bdx** [comment]
Thx!
