### ISSUE TITLE
./scripts/new_webmachine.sh will generate old deps config

### ISSUE THREAD

**Issue by nati** [webmachine/webmachine#135]
I got following error when I run ./scripts/new_webmachine.sh with master then make it.

ERROR: Dependency dir /Users/nachiueno/work/try-webmachine/snowflake/deps/webmachine failed application validation with reason:
{version_mismatch,{"/Users/nachiueno/work/try-webmachine/snowflake/deps/webmachine/src/webmachine.app.src",
                   {expected,"1.9.*"},
                   {has,"1.10.0"}}}.

It looks like generated rebar.config has old value.

**Comment by kellymclaughlin** [comment]
Fix is merged. Thanks for the report.
