### ISSUE TITLE
Skeleton code incorrect

### ISSUE THREAD

**Issue by sridhraj** [webmachine/webmachine#138]
Change 
application:set_env(webmachine, webmachine_logger_module, webmachine_logger),
to 
application:set_env(webmachine, webmachine_logger_module, webmachine_log),

in two places in the file
webmachine/priv/templates/src

**Comment by joedevivo** [comment]
This is no longer a problem. Try the [rebar3 template](https://github.com/webmachine/webmachine-rebar3-template)
