### ISSUE TITLE
webmachine_mochiweb crashes with unsupported requests

### ISSUE THREAD

**Issue by jcapricebasho** [webmachine/webmachine#149]
The webmachine_mochiweb process crashes when handling unsupported requests that use supported methods.

```
2013-05-24 04:04:20.195 [error] <0.18313.2328> CRASH REPORT Process <0.18313.2328> with 0 neighbours crashed with reason: no function clause matching mochiweb:new_request({#Port<0.22901381>,{'GET',".\\.\\.\\.\\.\\.\\.\\.\\.\\.\\/windows/win.ini",{1,1}},[{'Accept',"i..."},...]}) line 51
```

This is a result of the request not matching any of mochiweb's new_request function clauses, and differs in how webmachine handles requests using unsupported methods.

https://github.com/basho/mochiweb/blob/1.5.1p3/src/mochiweb.erl#L51

riak_core_sup will restart webmachine_mochiweb when it crashes, however during these instances clients can get `[Errno 104] Connection reset by peer` responses.

I will attach the example requests when available.

**Comment by djnym** [comment]
This looks like this fix I had against mochiweb

https://github.com/mochi/mochiweb/pull/107

The issue is actually a bug in OTP, which is fixed in R16B (https://github.com/erlang/otp/commit/6aa9e71dbb279a172b5a2c86f28cbfada1b68080), but the fix can be backported (I've done so in our other mochiweb systems).

Hope that helps.

**Comment by joedevivo** [comment]
@jcapricebasho is this ok now that we're all in the world of R16B and higher?

**Comment by beerriot** [comment]
It looks like the example requests were never attached, but as Joe said, we're now using R16B and higher, as well as mochiweb beyond the release with the patch mentioned (2.6.0). Closing.
