### ISSUE TITLE
script/new_webmachine generates rebar.config with webmachine 1.9*

### ISSUE THREAD

**Issue by edwardt** [webmachine/webmachine#162]
ERROR: Dependency dir /opt/ejabberd-modules/presence_rest_api/deps/webmachine failed application validation with reason:
{version_mismatch,{"/opt/ejabberd-modules/presence_rest_api/deps/webmachine/src/webmachine.app.src",
                   {expected,"1.9.*"},
                   {has,"1.10.3"}}}.

**Comment by joedevivo** [comment]
script/new_webmachine no longer exists. the [webmachine-rebar3-template](https://github.com/webmachine/webmachine-rebar3-template) generates a rebar.config with webmachine 1.10.*
