### ISSUE TITLE
Server-sent events support

### ISSUE THREAD

**Issue by fgallaire** [webmachine/webmachine#167]
Could webmachine have a server-sent events support ?

**Comment by seancribbs** [comment]
It's trivial, see the example here: https://github.com/cmeiklejohn/webmachine-tutorial/blob/master/src/tweeter_wm_tweets_resource.erl

**Comment by fgallaire** [comment]
In fact, the subliminal question is : could riak have a server-sent events support through webmachine ?
An easy way to push the datas from the cluster to the client, with no coding.

**Comment by seancribbs** [comment]
Yes, but it would require a decent amount of custom code: an event handler,
a new resource and likely a commit hook. It's not something we have a great
demand for right now.

On Fri, Sep 27, 2013 at 7:16 AM, Florent Gallaire
notifications@github.comwrote:

> In fact, the subliminal question is : could riak have a server-sent events
> support through webmachine ?
> An easy way to push the datas from the cluster to the client, with no
> coding.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/webmachine/issues/167#issuecomment-25240927
> .

## 

Sean Cribbs sean@basho.com
Software Engineer
Basho Technologies, Inc.
http://basho.com/

**Comment by fgallaire** [comment]
The Riak Control documenation says :

```
Event streaming

Currently Riak Control uses a pull model to gather information about the cluster. While this isn’t a performance 
issue, we very much want to make it a push-system. As things happen to the cluster, the cluster should notify Riak 
Control of the changes, which in-turn will notify the user.
```

Riak Control is written with the Ember.js framework. I think that Riak + SSE support could be the perfect fit with the javascript client frameworks like ember.js and AngularJS.

**Comment by seancribbs** [comment]
Sure, but that's not a webmachine issue. Opening the issue on Riak Control would be more appropriate.
