### ISSUE TITLE
Errors in resource init are hard to find

### ISSUE THREAD

**Issue by jbothma** [webmachine/webmachine#171]
Errors in resource init are difficult to find.

webmachine_mochiweb catches error class exceptions, and the default error handler only logs {error, Reason} - not the stacktrace, resource or the fact that it was in the init function of the resource (if it was that - it could be other things too).

errors in the other callbacks are easier to find because tracing can be turned on if the init succeeds, but crashes in logic e.g. deciding whether to turn on tracing or not are tricky to find without writing your own error handler.

Do you think logging the stack trace in the default handler would be ok or are you intentionally not logging that much there?

**Comment by beerriot** [comment]
Btw, thx for the report, JD. I've stumbled over this too many times for a fix to have taken this long.

**Comment by jbothma** [comment]
9 years later, nice job cleaning up :D
