### ISSUE TITLE
Clock Skew on 'undefined' handler

### ISSUE THREAD

**Issue by zkessin** [webmachine/webmachine#172]
In the case where a web request arrives and does not match any routing rule I am seeing that fairly often it leaves a result in the perf.log that has a negative time. This is often -1ms, but can be as much as -5ms. 

I assume that there is some form of clock skew going on here.

**Comment by beerriot** [comment]
I think we need more information here, like OS and OTP versions. My guess is that another process on the system (like NTP) is altering the system clock during a request. `webmachine_perf_log_handler` uses `webmachine_util:now_diff_milliseconds/2` to compute these times. The times it passes are from the `#wm_log_data` fields `start_time`, `end_time`, and `finish_time`.

```erlang
    TTPD = webmachine_util:now_diff_milliseconds(EndTime, StartTime),
    TTPS = webmachine_util:now_diff_milliseconds(FinishTime, EndTime),
```

Interestingly, when no routing rule is found, the latter two fields are `undefined`. For the TTPS (end to finish) value, this will always be zero:

```erlang
now_diff_milliseconds(undefined, undefined) ->
     0;
```

For the TTPD value (start to end), a fresh `os:timestamp` value is synthesized:

```erlang
now_diff_milliseconds(undefined, T2) ->
     now_diff_milliseconds(os:timestamp(), T2);
```

I initially expected a skew from calling `erlang:now/0` too much, but that start time is also an `os:timestamp` created in `webmachine_mochiweb`.

```erlang
    InitialLogData = #wm_log_data{start_time=os:timestamp(),
```

[The docs for `os:timetamp`](https://www.erlang.org/doc/man/os.html#timestamp-0) link to [notes on OS System Time](https://www.erlang.org/doc/apps/erts/time_correction.html#OS_System_Time) that state explicitly that no limits on its adjustment forward or backward - "That is, time warps may be observed."

R18 introduced a [new time API](https://www.erlang.org/doc/apps/erts/time_correction.html#The_New_Time_API) that is likely the solution to this problem. The Do's & Dont's for this new API suggest that [measuring elapsed time should be done with `erlang:monotonic_time/0,1`](https://www.erlang.org/doc/apps/erts/time_correction.html#Dos_and_Donts_Measure_Elapsed_Time). It seems like [Multi-Time Warp Mode](https://www.erlang.org/doc/apps/erts/time_correction.html#multi-time-warp-mode) should also be enabled while doing this? The main danger I see is that the docs for `webmachine_util:now_diff_milliseconds/2` make specific note of the performance that function achieves by not using bignums. Are Erlang monotonic times small enough to avoid penalty?
