### ISSUE TITLE
Return 406 status code on not supported content type

### ISSUE THREAD

**Issue by madtrick** [webmachine/webmachine#188]
The documentation says the following regarding request content type negociation:

>  For example, if a client request includes an Accept header with a value that does not appear as a first element in any of the return tuples, then a 406 Not Acceptable will be sent.

Imagine the following resource which only supports `application/json` as content-type:

``` erlang
-module(pera_processes_resource).

-export([init/1]).
-export([to_json/2]).
-export([content_types_provided/2]).

-include_lib("webmachine/include/webmachine.hrl").

%%========================================
%% Webmachine resource functions
%%========================================
init([]) -> {ok, undefined}.

content_types_provided(Req, Context) ->
  {[{"application/json", to_json}], Req, Context}.

%%========================================
%% Resource functions
%%========================================

to_json(ReqData, State) ->
  {"{'a' : 1}", ReqData, State}.
```

A request from the browser to this resource will include the following `Accept` header:

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
```

I expected `webmachine` to response with a `406` status code because the `Accept` header didn't include `application/json`. But `webmachine` replied as if the `json` type was supported. This was its response:

```
Content-Length:9
Content-Type:application/json
Date:Fri, 31 Jan 2014 18:31:15 GMT
Server:MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)
```

Is this a bug or am I missing/misunderstanding something?

**Comment by seancribbs** [comment]
`*/*;q=0.8` matches `application/json`, even with the lower priority.

**Comment by madtrick** [comment]
Didn't notice. My bad

Thank you
