### ISSUE TITLE
Is it possible to get the original file for the flow diagram?

### ISSUE THREAD

**Issue by Altreus** [webmachine/webmachine#194]
Not an issue, just wondered whether a copy of the original binary for the flow PNG were available somewhere. I'd like to hack at it without having to recreate the whole thing first. Would be appreciated.

**Comment by shino** [comment]
@Altreus Do you mean https://github.com/basho/webmachine/blob/develop/priv/trace/http-headers-status-v3.png ?

**Comment by Altreus** [comment]
@shino That's right - is there a file formatted for some app that made it? Thanks

**Comment by shino** [comment]
@Altreus Sorry, I don't know about that.

**Comment by christopheradams** [comment]
@Altreus That version of the http headers status by Alan Dean has been preserved at [for-GET/http-headers-status](https://github.com/for-GET/http-headers-status).
