### ISSUE TITLE
meck 0.8.1p please

### ISSUE THREAD

**Issue by reppolice** [webmachine/webmachine#200]
Currently webmachine is not using the latest meck patch, the latter addresses among others warnings that turn critical in OTP 18, and Heroku refuses to build. Please pretty please? My understanding is that the patch includes a couple of macros and breaks nothing.

**Comment by kuenishi** [comment]
I created [17.0 branch](https://github.com/basho/webmachine/tree/ku-17.0) temporarily. Hope it helps.

**Comment by joedevivo** [comment]
rebar3 now only pulls in the freshest `meck`. As of this moment, that is 0.8.3.
