### ISSUE TITLE
412 Precondition Failed can cause forcible socket disconnect.

### ISSUE THREAD

**Issue by lukebakken** [webmachine/webmachine#211]
In certain scenarios a client that sends the `If-Unmodified-Since` can result in the server (Riak) sending the `412` response before the client sends all body data. In this case, the server forcibly resets the connection, causing an exception in the client (Apache HttpClient). A NetBeans project that can be used to reproduce the issue is available here:

https://www.dropbox.com/s/00ejs3faivbxm60/HttpClientTest.zip?dl=0

![riak-connection-ok](https://cloud.githubusercontent.com/assets/514926/4018704/2e5d870c-2a53-11e4-8169-0a309558f871.png)

![riak-connection-reset](https://cloud.githubusercontent.com/assets/514926/4018705/2e64b3a6-2a53-11e4-94c9-28261a294e94.png)

**Comment by seancribbs** [comment]
That would more likely be a bug in Apache's HttpClient, but it does seem like webmachine or mochiweb should at least read the entire body so the _next_ request doesn't fail. Alternately, webmachine could choose to close the socket but I don't see a good reason to do that in the general case.

**Comment by shino** [comment]
If RST is only the issue, `Expect: 100-Continue` may help.
Webmachine can treat 100 Continue [1]. I don't know how
Apache HTTP Client behaves, but at least doc says it supports [2].

A question at this point is whether TCP Connection Keep Alive is also an issue.
If so, as Sean said, webmachine should consume request body.
One counter example is Riak CS, which may accept entity body up to 5GB.

[1] Expect 100 to Riak https://gist.github.com/shino/11419f6f53db02003552
[2] http://hc.apache.org/httpclient-3.x/performance.html#Expect-continue_handshake

**Comment by lukebakken** [comment]
`Expect: 100-Continue` is not being sent as a header by the Apache HttpClient

**Comment by lukebakken** [comment]
@seancribbs pointed out this as well:

https://github.com/basho/mochiweb/blob/master/src/mochiweb_http.erl#L59-L80

**Comment by michellep-basho** [comment]
Adding that this is a customer reported issue.

**Comment by beerriot** [comment]
I think this is a dupe of #168.
