### ISSUE TITLE
Custom logic for Range headers?

### ISSUE THREAD

**Issue by nickretallack** [webmachine/webmachine#212]
I noticed it handles Range requests in the source code, but there's no callback or step in the flowchart for customizing the behavior here.  I haven't experimented with this yet, but does webmachine slice up my response for me?  Would it behave badly if I tried to slice up the response myself, for performance reasons?

Here's a simple example of something you might want to do, as an application developer:

You present a resource on webmachine.  It is actually represented as a series of files on disk, with known sizes and ordering.  When you get a range request, you look at the start byte to determine at which point in which file you need to start reading, and at which point in which file you can stop reading.

If you attempted to implement this on webmachine, would it thwart you by slicing up your response again based on the range header after you already sliced it yourself?  Would it cause bad things to happen to the other headers?  Or is it totally up to you to implement the slicing behavior?

**Comment by nickretallack** [comment]
Hm.  I guess this could be handled by returning a file-like object and handling the reads internally, which would put this outside webmachine's domain...

**Comment by shino** [comment]
May or may not an good answer for you, I know one example, Riak CS. [1]
It parse range header and fetch contents from Riak to satisfy the range by itself.

[1] https://github.com/basho/riak_cs/blob/develop/src/riak_cs_wm_object.erl#L147

**Comment by beerriot** [comment]
For the basic body and stream body responses, yes Webmachine does the slicing for you, and expects you to produce the entire body. But there are two options for more efficient range serving, in additional to the manual one that shino noted.

The first is that Webmachine will automatically handle pulling bits off disk from a file for you. Return `{file, IoDevice}`, where `IoDevice` is an open file handle, and Webmachine will read just the requested ranges out of the file and push them out in the response for you.

The second is the `{known_length_stream, Size, BodyFun}` response type. The function passed as the third element should take two arguments: a `Start` offset and an `End` offset. For range queries, Webmachine will call the function with the appropriate offsets, and the function only needs to produce the bytes between them.
