### ISSUE TITLE
Cache-Control?

### ISSUE THREAD

**Issue by nickretallack** [webmachine/webmachine#213]
I don't see anything about the Cache-Control header in webmachine.  Can I set resources to no-cache, or set their max-age beyond the maximum value allowed by the Expires header?

**Comment by seancribbs** [comment]
Yes, you can manually set the Cache-Control header at any point, but `finish_request` might be the best callback in which to do so. Example:

``` erlang
finish_request(RD, State) ->
  {ok, wrq:set_resp_header("cache-control", "no-cache, private, max-age=0", RD), State}.
```
