### ISSUE TITLE
Content negotiation for error pages?

### ISSUE THREAD

**Issue by nickretallack** [webmachine/webmachine#214]
If someone requests html and there is an error, I'd like to display it as html, but if they request json, I'd like the error page to be in JSON.  Are there to_html/to_json functions for error responses?  Perhaps to_error_json?  This function would need to receive some indication of the error code it was generating for, in addition to the error string you may have returned from the function that caused the error.

**Comment by beerriot** [comment]
Error handlers only expose `render_error/3`, and it is up to the to choose the content type to send (and to set the header for it, accordingly!). The included `webmachine_error_handler` always sends HTML.

If you would like to negotiate the content type of the error you send, `webmachine_util:choose_media_type/2` will figure out the preferred type for you.

I don't think we'll add content type negotiation to the error handler calls, in general, though. The error handler is only called for 404 and 500 errors. Most apps want to bail as quickly as possible on 500, so they prefer to just shove anything out in a response and be done. That also reduces the chance of a cascade error in the error handler.
