### ISSUE TITLE
A ping like resource for node membership would be very helpful

### ISSUE THREAD

**Issue by bsparrow435** [webmachine/webmachine#223]
Some users doing automatic rollouts would like a ping-like resource for cluster membership. I.e. Load balancer can use this ping to determine when it's safe to start writing/reading to a node.

**Comment by binarytemple** [comment]
+1

**Comment by vinoski** [comment]
Isn't this a Riak-specific feature request, rather than a webmachine feature request? Or is there something missing from webmachine that prevents such a Riak resource from being implemented?

**Comment by joedevivo** [comment]
@bsparrow435 cool to close this?

**Comment by bsparrow435** [comment]
Yep go ahead, we have some work in the mix in riak_core for this/
