### ISSUE TITLE
What happenned to dispatch.conf ?

### ISSUE THREAD

**Issue by altitude** [webmachine/webmachine#224]
To be honest I'm a fairly new Erlang & Webmachine user trying to figure out this whole thing.

The wiki's [quickstart](https://github.com/basho/webmachine/wiki/Quickstart#next-steps) tells us to check the `priv/dispatch.conf` file.

However, it seems that `dispatch.conf` was removed from the new project template (see [removed](https://github.com/basho/webmachine/commit/fd3070fcba70adb7993f36add08760337470b57f)).

So, what's the deal with dispatch.conf ?

Thanks !

**Comment by vinoski** [comment]
On Wed, Nov 12, 2014 at 5:05 PM, Clément Salaün notifications@github.com
wrote:

> To be honest I'm a fairly new Erlang & Webmachine user trying to figure
> out this whole thing.
> 
> The wiki's quickstart
> https://github.com/basho/webmachine/wiki/Quickstart#next-steps tells us
> to check the priv/dispatch.conf file.
> 
> However, it seems that dispatch.conf fd3070f
> https://github.com/basho/webmachine/commit/fd3070fcba70adb7993f36add08760337470b57f
> and is removed from the new project template.
> 
> So, what's the deal with dispatch.conf ?
> 
> Have a look here:

https://github.com/basho/webmachine/blob/develop/priv/templates/src/wmskel_config.erl#L9-L12

When you use the new_webmachine.sh script to generate a new project, the
skeleton above is used to generate an {{appid}}_config.erl file for you,
and you can fill in the dispatch() function in that generated file to add
your dispatch table.

--steve

**Comment by altitude** [comment]
Ah, it all makes sense now. Thanks for your help !
