### ISSUE TITLE
Check CI status

### ISSUE THREAD

**Issue by mbbroberg** [webmachine/webmachine#245]
We just transferred ownership from Basho to this account and forked back. From past experiences, this breaks CI. Please check the build system and let me know if you need permissions to edit anything.

**Comment by seancribbs** [comment]
Travis seems to be working. :smile: Are you concerned about buildbot?

**Comment by mbbroberg** [comment]
Nope @seancribbs! I actually fixed this with #247 and forgot to add the "resolves" note. We're all set here.
