### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by sdebnath** [webmachine/webmachine#253]
With all the massive changes recently, can we get a new release tag so that folks can standardize on what to pull down? Or are we waiting on more fixes before a new release is pushed?

Thanks!

**Comment by sdebnath** [comment]
@seancribbs can we generate a new tag for the latest set of commits? Unless we are holding back for a pending commit? Thanks.

**Comment by bookshelfdave** [comment]
+1

**Comment by djnym** [comment]
@seancribbs any chance there will ever be new tagged releases?  It's been years since the last one.

**Comment by djnym** [comment]
Actually, looks like a 1.10.9 tag showed up in April which I missed, @seancribbs you should feel free to close this.
