### ISSUE TITLE
500 error when is_authorized returns {false, RD, Ctx} as described in docs

### ISSUE THREAD

**Issue by sdebnath** [webmachine/webmachine#254]
The wiki (https://github.com/webmachine/webmachine/wiki/Resource-Functions#is_authorized) mentions that we should return {true, RD, Ctx} on authorized calls and {false, RD, Ctx} on calls that are not authorized. Doing so results in 500 internal server error when wrq module tries to set response headers:

http://pastebin.com/8SFyawin

**Comment by bookshelfdave** [comment]
I'm not sure if it's actually checking for a boolean:
https://github.com/webmachine/webmachine/blob/6534ee70b0c5c6b0382625d6115dbb15c0992632/src/webmachine_decision_core.erl#L213

On Wed, Oct 7, 2015 at 3:53 PM, Shawn Debnath notifications@github.com
wrote:

> The wiki (
> https://github.com/webmachine/webmachine/wiki/Resource-Functions#is_authorized)
> mentions that we should return {true, RD, Ctx} on authorized calls and
> {false, RD, Ctx} on calls that are not authorized. Doing so results in 500
> internal server error when wrq module tries to set response headers:
> 
> http://pastebin.com/8SFyawin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/webmachine/webmachine/issues/254.

## 

Dave
https://github.com/metadave/

**Comment by sdebnath** [comment]
That makes sense, I can create a PR unless you want to do it.

**Comment by seancribbs** [comment]
Docs are fixed. Thanks for bringing it to our attention!
