### ISSUE TITLE
erlydtl failed application validation with reason:

### ISSUE THREAD

**Issue by peter0072000** [webmachine/webmachine#259]
I'm get demo from https://github.com/webmachine/webmachine-demo, and i get error after make

deps/erlydtl failed application validation with reason:
{missing_app_file,"/media/webmachine-demo/deps/erlydtl"}.
ERROR: 'get-deps' failed while processing /media/webmachine-demo: rebar_abort

**Comment by seancribbs** [comment]
It looks like some things have changed in erlydtl when we weren't watching. For now, try going into deps/erlydtl and running `make` there, and then running it again from the top-level project.

**Comment by peter0072000** [comment]
thanks @seancribbs  reply.

after that , i got new error :

==> emysql (compile)
Generating "include/crypto_compat.hrl" ...
...supports cryto:hash/2
...no changes needed to "include/crypto_compat.hrl". Skipping writing new file
==> erlydtl (compile)
make[1]: Entering directory `/media/webmachine/demo/deps/merl'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/media/webmachine/demo/deps/merl'
ERROR: /media/webmachine/demo/deps/erlydtl/.rebar/erlcinfo file version is incompatible. expected: 1 got: 2
ERROR: compile failed while processing /media/webmachine/demo/deps/erlydtl: rebar_abort

**Comment by peter0072000** [comment]
it's ok after updating rebar.config:

{deps,
  [
    {webmachine, "._", {git, "git://github.com/echenonline/webmachine", {tag, "1.10.8"}}}
    ,{riakc, "._", {git, "git://github.com/echenonline/riak-erlang-client", {tag, "2.3.0-timeseries"}}}
    ,{emysql,"._",{git,"git://github.com/echenonline/Emysql.git", {tag, "v0.4.1"}}}
    ,{erlydtl, "._", {git, "git://github.com/echenonline/erlydtl.git", {tag, "0.10.0"}}}
  ]
}.

**Comment by beerriot** [comment]
I'm hoping this is resolved by webmachine/webmachine-demo#1
