### ISSUE TITLE
how to parse parameters with POST method on basho/webmachine 

### ISSUE THREAD

**Issue by peter0072000** [webmachine/webmachine#260]
Dears
   Now I'm using demo on https://github.com/basho/webmachine , and using the following rebar.config , and  using the sample code from http://tkyshm.hatenablog.com/entry/2014/05/31/230842
but i can't parse correct params with POST method 

![image](https://cloud.githubusercontent.com/assets/16733937/12452920/c48f44a4-bfcb-11e5-8c94-a599d022e2d2.png)

rebar.config:

%start
{deps,
    [
        {webmachine, ".", {git, "git://github.com/echenonline/webmachine", {tag, "1.10.8"}}}
        ,{riakc, ".", {git, "git://github.com/echenonline/riak-erlang-client", {tag, "2.3.0-timeseries"}}}
        ,{emysql,".",{git,"git://github.com/echenonline/Emysql.git", {tag, "v0.4.1"}}}
        ,{erlydtl, ".", {git, "git://github.com/echenonline/erlydtl.git", {tag, "0.10.0"}}}
    ]
}.
%end

response data:
<html>
    <head>
        <title>500 Internal Server Error</title>
    </head>
    <body>
        <h1>Internal Server Error</h1>The server encountered an error while processing this request:
        <br>
            <pre>{error,
    {error,
        {case_clause,
            <<"------WebKitFormBoundaryhq4FipjsrL8spnUD\r\nContent-Disposition: form-data; name=\"sdfsdf\"\r\n\r\nsdf\r\n------WebKitFormBoundaryhq4FipjsrL8spnUD\r\nContent-Disposition: form-data; name=\"sdf\"\r\n\r\ns123\r\n------WebKitFormBoundaryhq4FipjsrL8spnUD--\r\n">>},
        [{mochijson2,tokenize_number,4,
             [{file,"src/mochijson2.erl"},{line,495}]},
         {mochijson2,tokenize_number,2,
             [{file,"src/mochijson2.erl"},{line,480}]},
         {mochijson2,decode1,2,[{file,"src/mochijson2.erl"},{line,326}]},
         {mochijson2,json_decode,2,[{file,"src/mochijson2.erl"},{line,321}]},
         {appname_ebooks_resource,create_resource,2,
             [{file,"src/appname_ebooks_resource.erl"},{line,85}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,186}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,142}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]}]}}
            </pre>
            <P>
                <HR>
                    <ADDRESS>mochiweb+webmachine web server</ADDRESS>
                </body>
            </html>

**Comment by seancribbs** [comment]
Two things:
1. You are setting `application/json` as the Content-Type, but sending form data.
2. You are sending form data in the `multipart/form-data` format (note the multipart boundary in the body), not `application/x-www-form-urlencoded`.

Your webmachine resource MUST accept the appropriate content type for anything to happen. After that has been accepted, you can validate the body in your acceptor function. Obviously the call you made will not parse JSON from `multipart/form-data`, so you should probably use a try/catch expression and use `{halt, 400}` if the body does not parse as JSON.

**Comment by peter0072000** [comment]
@seancribbs , thank you very much!

Now, i met another problem: It can response data with GET method , but POST can't. And the code is the same as. Is it forget  somewhere settings ?

%% GET-----It's OK
create_resource(#wm_reqdata{method = 'GET'} = Req, State) ->
SS = [wrq:req_body(Req)],
io:format("Request Data: ~n ~p~n",SS), 
Resp =  json_body(wrq:req_qs(Req)),
{Resp, Req, State};

%% POST-------Can't response to request client
create_resource(#wm_reqdata{method = 'POST'} = Req, State) ->
% TODO: create process
SS = [wrq:req_body(Req)],
io:format("Request Data: ~n ~p~n",SS), 
Resp =  json_body(wrq:req_qs(Req)),
{Resp, Req, State};

**Comment by beerriot** [comment]
An example of parsing form data can be found in [wriaki](https://github.com/basho-labs/wriaki/). The `wiki_resource` has specified that it has a body processing function that accepts `application/x-www-form-url-encoded` called `accept_form`, and that function calls a helper called `article_from_rd`, which looks like this:

```erlang
article_from_rd(RD, Ctx) ->
    Body = mochiweb_util:parse_qs(wrq:req_body(RD)),
    Text = list_to_binary(proplists:get_value("text", Body)),
    Msg = list_to_binary(proplists:get_value("msg", Body)),
    Vclock = proplists:get_value("vclock", Body),
    UserCtx = load_username(RD, Ctx),
    article:create(search_path(RD), Text, Msg, Vclock,
                   UserCtx#ctx.username).
```
