### ISSUE TITLE
Webmachine error when applying a release upgrade

### ISSUE THREAD

**Issue by marjaimate** [webmachine/webmachine#278]
When generating a release (using rebar3 and relx), webmachine starts fine, and works as expected. Although, when generating a release upgrade, and installing the upgrade, webmachine produces the following error for all their workers:

```
(some_app@127.0.0.1)4> 10:15:56.524 [error] CRASH REPORT Process <0.5736.317> with 0 neighbours crashed with reason: no case clause matching undefined in webmachine_mochiweb:new_webmachine_req/1 line 125
```

To resolve that, I need to stop the node, rebuild a new release and start again. Could you advise what could cause this behavior?

Note: the relup file's instructions, and the changed code is unrelated to webmachine resources and workers.

**Comment by seancribbs** [comment]
Could you be more specific about which version (SHA or tag) you are using?

**Comment by marjaimate** [comment]
@seancribbs sure thing, my rebar.lock has these in it for mochiweb and webmachine

```
[
 %% ...
 {<<"mochiweb">>,
  {git,"https://github.com/mochi/mochiweb.git",
       {ref,"0ca0375bead0f1857f3b17652b1aca6592284fe1"}},
  0},
 {<<"webmachine">>,
  {git,"git://github.com/webmachine/webmachine.git",
       {ref,"6c4265808d8d307d76f28483f5eaada7d261ea18"}},
  0}].
```

**Comment by seancribbs** [comment]
This appears to be related to the defaults defined in [`webmachine.app`](https://github.com/webmachine/webmachine/blob/6c4265808d8d307d76f28483f5eaada7d261ea18/src/webmachine.app.src#L20). I'm uncertain what steps your release upgrade takes, but it seems to suggest that the default is cleared or removed.

**Comment by marjaimate** [comment]
Ok, thanks, how can I make sure that this doesn't happen? What would I need to add to my relup file(s)?

I'm using the relup generated using relflow, example below:

```
{"20161212.100124",
 [{"20161206.203647",[],
   [{load_object_code,{my_app,"20161212-100124-relflow",
                              [some_module,
                               some_module]}},
    point_of_no_return,
    {load,{some_module,brutal_purge,brutal_purge}},
    {load,{some_module,brutal_purge,brutal_purge}}]}],
 [{"20161206.203647",[],[point_of_no_return]}]}. 
```
