### ISSUE TITLE
Typo in the Resource Functions wiki page, under charsets_provided

### ISSUE THREAD

**Issue by grantwinney** [webmachine/webmachine#283]
There's a typo in the [Resource Functions](https://github.com/webmachine/webmachine/wiki/Resource-Functions) wiki page:

> ### charsets_provided

    -spec content_types_accepted(rd(), state()) -> {no_charset | [{Charset::string(), Converter}], rd(), state()}
               when Converter :: fun((iodata()) -> iodata()).

The name of the function should be `charsets_provided` not `content_types_accepted`.

**Comment by justinsheehy** [comment]
Good catch, thanks!

Fixed.

**Comment by grantwinney** [comment]
Thanks for fixing that so quickly. I'll go ahead and close this.
