### ISSUE TITLE
rebar3 compile failed on OSX

### ISSUE THREAD

**Issue by pito-svk** [webmachine/webmachine#284]
after running rebar3 compile I got the following error:

> ===> Verifying dependencies...
===> Compiling webmachine
===> Compiling _build/default/lib/webmachine/src/webmachine_request.erl failed
_build/default/lib/webmachine/src/webmachine_request.erl:651: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

My dependency is the following:

```erlang
{webmachine, "1.10.*", {git, "git://github.com/webmachine/webmachine", {branch, "master"}}}
```

Do you know what can be the issue? 

Thanks.

**Comment by seancribbs** [comment]
Be sure to update to the latest. If you check the `webmachine_request` module on `master`, you'll see we use `crypto:strong_rand_bytes/1`.

**Comment by pito-svk** [comment]
Resolved thx
