### ISSUE TITLE
`send_response` should come before `finish_request`

### ISSUE THREAD

**Issue by zzantozz** [webmachine/webmachine#290]
In [`webmachine_decision_core:finish_response()`](https://github.com/webmachine/webmachine/blob/9c9bd3a1c7b1dbb04e356314fa5cd9a49e1910c5/src/webmachine_decision_core.erl#L90), it goes like
```
    ...
    resource_call(finish_request),
    wrcall({send_response, CodeAndPhrase}),
   ...
```
In the case of a streamed response, like `{stream, Something}`, this can lead to the `finish_request` callback happening before the stream has been fully consumed, which, in turn, can break things if your stream is some kind of stateful thing, like a database cursor, which has to be shut down after the request is "finished".

Maybe I'm doing something wrong and/or don't know about some other important concept here, but shouldn't `finish_request` only be called after the request is *really* finished? Is there another way to solve this problem?

**Comment by seancribbs** [comment]
`finish_request` is typically used to fixup responses (add headers, etc) before they are sent. In the case that your stream is using a resource, it should clean them up when the stream terminates, not in `finish_request`.

**Comment by zzantozz** [comment]
@seancribbs How would you define "stream terminates" when the length is unknown? What if the connection is severed before fully consuming the stream? Also, what about other potential request-related resources that shouldn't be cleaned up until the body is finished streaming? Isn't it part of the http server's job to indicate that a request has been completely serviced?

**Comment by seancribbs** [comment]
You don't need to worry about the client disconnecting because each connection is handled by a separate process. If your resources (processes) that need cleanup are linked to the webmachine resource/connection, teardown will be automatic. This is an OTP principle that you can take advantage of.

Remember also that you have complete access to the request state in `finish_request`! It is not uncommon to put a flag or other term in the state to signify that you are streaming and should not reclaim resources in use.

**Comment by zzantozz** [comment]
> If your resources (processes) that need cleanup are linked to the webmachine resource/connection, teardown will be automatic.

Not from what I've seen. On the one hand, in socket-related error cases, [mochiweb tends to `exit(normal)`](https://github.com/basho/mochiweb/blob/master/src/mochiweb_socket.erl#L145), which isn't going to propagate to linked processes. In non-error cases, the [`mochiweb_acceptor`](https://github.com/basho/mochiweb/blob/master/src/mochiweb_acceptor.erl) is pooled and reused by the [`mochiweb_socket_server`](https://github.com/mochi/mochiweb/blob/master/src/mochiweb_socket_server.erl), meaning a single acceptor could handle many requests, so that's useless as a signal for when a request is finished. Am I missing something?

> Remember also that you have complete access to the request state in finish_request! It is not uncommon to put a flag or other term in the state to signify that you are streaming and should not reclaim resources in use.

Yes, that's true. What I'm looking for here, though, is a signal that the request *is* finished so that I *can* reclaim resources.

**Comment by zzantozz** [comment]
On top of all this, webmachine itself isn't completely consistent. The whole [`finish_response` function](https://github.com/webmachine/webmachine/blob/master/src/webmachine_decision_core.erl#L87) that I partially quoted earlier, goes like this:
```erlang
finish_response({Code, _}=CodeAndPhrase, Resource, EndTime) ->
    put(code, Code),
    wrcall({set_response_code, CodeAndPhrase}),
    resource_call(finish_request),
    wrcall({send_response, CodeAndPhrase}),
    RMod = wrcall({get_metadata, 'resource_module'}),
    Notes = wrcall(notes),
    LogData0 = wrcall(log_data),
    LogData = LogData0#wm_log_data{resource_module=RMod,
                                   end_time=EndTime,
                                   notes=Notes},
    spawn(fun() -> do_log(LogData) end),
    webmachine_resource:stop(Resource).
```
Note that `EndTime` is passed in, having been set earlier, even though the response hasn't been sent yet, so the log won't have accurate times in it.

I understand now why the `finish_request` callback shouldn't be moved, but at this point, I'd propose a new resource callback function, like `response_finished` to be called after the `wrcall({send_response, CodeAndPhrase})`, which I believe blocks until the response is completely sent.

**Comment by beerriot** [comment]
I think a `response_finished` callback could be a nice addition. But in the meantime, I've just submitted a pull request to better enable the facilities that Sean pointed to. Since upgrading to mochiweb v3.1.1, errors detected at the mochiweb level now cause the request to exit with reason `{shutdown, Error}` instead of `normal`. PR #330 prevents webmachine from exiting `normal` on errors returned by `mochiweb_socket:send` as well. This should mean that resources in linked processes will now cleanup, as expected.

**Comment by beerriot** [comment]
I'm going to close this for now, since resource cleanup at the end of request processing should be improved now. If someone wants to reignite the conversation about an additional resource callback, either reopen or file a new issue.
