### ISSUE TITLE
Exposing the actual socket?

### ISSUE THREAD

**Issue by choptastic** [webmachine/webmachine#296]
Hey Sean,

A while back, this PR was accepted into the dev branch, but that dev branch was apparently never merged into master.

https://github.com/webmachine/webmachine/pull/175

Any chance this could be done again?

**Comment by choptastic** [comment]
I'm willing to re-issue the PR if necessary. Just let me know what you think!

**Comment by seancribbs** [comment]
Might have been lost in the transition outside Basho. If it's straightforward, I'll just forward-port it to master. Thanks for the heads-up!

**Comment by choptastic** [comment]
Great! Thanks. I'll check out the big merge today and make sure it all works as expected. Perfect timing as I'm also finishing updates for a new version of simple_bridge (which is what this was originally needed for).
