### ISSUE TITLE
Passing socket options through to mochiweb

### ISSUE THREAD

**Issue by martinsumner** [webmachine/webmachine#299]
The configuration guidance states that socket options can be passed through to mochiweb - https://github.com/webmachine/webmachine/wiki/Configuration#socket-options.

I was trying to see if I could set the `recbuf` option (which is needed to handle issues with large http headers otherwise being rejected if they're bigger than the buffer).  I couldn't see how these socket options are picked up (e.g. `nodelay`).

I have it working by adding some extra code into `webmachine_mochiweb:start/1` to do an application:get_env for the recbuf option.  But I'm guessing I've missed something, as there's no such logic for the other socket options (i.e. `nodelay` and `backlog`).  What is the right way of getting webmachine to detect socket options in the configuration and pass them on to mochiweb?

**Comment by dhull** [comment]
It looks to me like [`webmachine_mochiweb:get_wm_options`](https://github.com/webmachine/webmachine/blob/master/src/webmachine_mochiweb.erl#L204) returns all of the unparsed options as the last element of its return value (`RestOptions`) and they get passed to `mochiweb_http:start`. So, as with `nodelay` and `backlog`, all you should have to do is add the `recvbuf` option to webmachine's configuration and it will be passed through.

**Comment by martinsumner** [comment]
Ah OK.  Sorry, I didn't spot that.   Thanks for clarifying.
