### ISSUE TITLE
webmachine can't build with erlang 23.0.3

### ISSUE THREAD

**Issue by ghost** [webmachine/webmachine#308]
Compiling _build/default/lib/webmachine/src/webmachine_resource.erl failed
_build/default/lib/webmachine/src/webmachine_resource.erl:188: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace

erlang's version is 23.0.3 ,and rebar'version is 3.13.2

**Comment by gumtu** [comment]
i am running OTP22 and encountered this exact same error message when following the instructions in the "Quick Start" section of README.md.
these instructions specify cloning the webmachine/webmachine-rebar3-template repo which has a rebar.config file that builds a project skeleton.

in the top-level directory of that repo, the rebar.config file lists a dependency on the "develop" branch of the webmachine repo.
the develop branch of the webmachine repo is older than the master branch.
on the develop branch, line 188 of src/webmachine_resource.erl calls erlang:get_stacktrace() but this call is not present in the same file on the master branch.

in the rebar.config file in the webmachine-rebar3-template repo, changing the dependency from "develop" to "master" prevents the compiler error and allows me to run the hello world demo app.

**Comment by samwar** [comment]
@seancribbs Is this project dead? Do we need to find a new fork of webmachine? It looks like nothing has been done to support versions of erlang past 21.

**Comment by seancribbs** [comment]
> @seancribbs Is this project dead? Do we need to find a new fork of webmachine? It looks like nothing has been done to support versions of erlang past 21.

Do what you will, but I don't have time right now to take on this work.
