### ISSUE TITLE
unable to compile webmachine using Erlang/OTP 26 (.1.2 - Erlang/OTP 26 [erts-14.1.1] ) on linux - debian 12

### ISSUE THREAD

**Issue by elsbiet** [webmachine/webmachine#343]
hi,

i've upgraded from erlang/otp25 to erlang/otp26 (.1.2) and now i'm unable to compile my app using rebar3 (rebar 3.22.1+build.5321.refa16f41ae on Erlang/OTP 26 Erts 14.1.1)
.

the compilation process terminates stating:

===> Compiling _build/default/lib/webmachine/src/webmachine_util.erl failed

and there no more information available.

furthermore there are warnings:

_build/default/lib/mochiweb/src/mochiweb_session.erl:145:13: Warning: crypto:block_encrypt/4 is removed; use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead
_build/default/lib/mochiweb/src/mochiweb_session.erl:150:5: Warning: crypto:block_decrypt/4 is removed; use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead
_build/default/lib/mochiweb/src/mochiweb_session.erl:154:5: Warning: crypto:hmac/3 is removed; use crypto:mac/4 instead
_build/default/lib/mochiweb/src/mochiweb_session.erl:158:5: Warning: crypto:hmac/3 is removed; use crypto:mac/4 instead

_build/default/lib/mochiweb/src/mochiweb_socket.erl:33:45: Warning: ssl:cipher_suites/0 is removed; use cipher_suites/2,3 instead

_build/default/lib/mochiweb/src/mochinum.erl:47:8: Warning: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.

===> Compiling webmachine
===> Compiling _build/default/lib/webmachine/src/webmachine_util.erl failed
_build/default/lib/webmachine/src/webmachine_util.erl:267:18: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
_build/default/lib/webmachine/src/webmachine_util.erl:270:10: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
_build/default/lib/webmachine/src/webmachine_util.erl:275:10: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
_build/default/lib/webmachine/src/webmachine_util.erl:299:9: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.

my rebar.config species 
{deps, [
..         
{webmachine, "1.10.*", {git, "https://github.com/webmachine/webmachine.git", {branch, "main"}}}
..
]}
.

what can i do to enable compilation using erlang/otp 26 (.1.2) and to get rid of the warnings?.

thanks in advance for your assistance.

best regards, elsbieth

**Comment by elsbiet** [comment]
i've applied the patch specified at https://github.com/webmachine/webmachine/commit/530c1d19727696a14040ab4c08d80fd7e58395d5 and now i can compile and run my app.

as i'm not very familiar with rebar3 it would be nice if someone could tell me how to automatically  pull commit 530c1d1 (which solved the issue).

thanks in advance,

elsbieth.

**Comment by seancribbs** [comment]
@elsbiet You should be able to remove the downloaded dependency and re-fetch, or you could try `rebar3 upgrade webmachine`. See http://rebar3.org/docs/commands/

**Comment by elsbiet** [comment]
'rebar3 upgrade webmachine' did the job.

 thanks a lot.
