### ISSUE TITLE
"make" failed  after doing the steps described in the "Quickstart"

### ISSUE THREAD

**Issue by kay-ou** [webmachine/webmachine#57]
./scripts/new_webmachine.sh mywebdemo /tmp
cd /tmp/mywebdemo
make
-->
Uncaught error in rebar_core: {'EXIT',{{badmatch,{error,badfile}},
                                       [{rebar_core,select_modules,3},
                                        {rebar_core,acc_modules,4},
                                        {rebar_core,process_dir,4},
                                        {rebar_core,process_commands,2},
                                        {rebar,main,1},
                                        {escript,run,2},
                                        {escript,start,1},
                                        {init,start_it,1}]}}

Ubuntu 11.04 + Erlang 5.7.4 + Webmchine 1.9.1

**Comment by davidmathei** [comment]
I had the same error. I cloned rebar https://github.com/basho/rebar and built rebar locally, installed it in my PATH and replaced the references to 

```
@./rebar
```

in the Makefile with

```
rebar
```

and things worked. Without investigating further I would suggest that the rebar version coming with webmachine was not matching my environment (R13B04 (erts-5.7.5)).
