### ISSUE TITLE
Client disconnects are not logged

### ISSUE THREAD

**Issue by beerriot** [webmachine/webmachine#59]
If a client disconnects during a streaming response (and maybe also during a non-streaming response, if the body is larger than the buffer?), the request will never reach the logger.

The issue is in `webmachine_request:send/2`: https://github.com/basho/webmachine/blob/master/src/webmachine_request.erl#L263-268

When not using ssl, the return value from `mochiweb_socket:send/2` when the client has disconnected is `{error, enotconn}`.  This falls to the catch-all match of `webmachien_request:send/2`, and the process is summarily terminated via `exit(normal)`, which prevents the calls to the logger that would normally follow sending the response.

When using ssl, the return value is instead `{error, closed}`, which is matched and ignored by the function.  The request will continue "sending" the rest of the response, and eventually call the logger.  A similar patch could be made for `{error, enotconn}`, though it is somewhat unfortunate that the extra work has to be done.
## Sample code

A resource that produces one byte per second, for ten seconds:

``` erlang

-module(logdis_resource).
-export([init/1, to_html/2]).

-include_lib("webmachine/include/webmachine.hrl").

init([]) -> {ok, undefined}.

to_html(ReqData, State) ->
    {{stream, {<<"a">>, fun() -> slow_response(10) end}}, ReqData, State}.

slow_response(0) ->
    {<<>>, done};
slow_response(N) ->
    timer:sleep(1000),
    {<<"a">>, fun() -> slow_response(N-1) end }.
```

A dumb Webmachine logger that prints "Logging access!" when it is triggered:

``` erlang
-module(logdis_logger).

-export([start_link/1, log_access/1]).

start_link(_) ->
    {ok, spawn(fun() -> receive never -> ok end end)}.

log_access(_) ->
    io:format("Logging access!~n").
```

Enable this dumb logger before your start the `webmachine_mochiweb` server:

``` erlang
    application:set_env(webmachine, webmachine_logger_module, logdis_logger)
```

Request the URL you pointed at that resource, and allow it to run for 10 seconds; you'll see 11 `a`s, and a "Logging access!" in the console.  Request it again, and kill your client before all 11 `a`s come back; you'll never see "Logging access!" in the console.  You can check that the process has, indeed, gone away by evaluating `length(processes())` while the client is connected, and again a second after you have disconnected it (because it has to _try_ to send another chunk before it can know about the disconnect).

**Comment by Vagabond** [comment]
Is this related?

https://github.com/basho/webmachine/pull/50

Or do you just want to avoid the error suppression in some cases?

**Comment by beerriot** [comment]
@Vagabond Unrelated, I believe, other than the fact that this is one of those two `exit(normal)`s you mentioned.  I'm concerned with the logger that's normally used to write access logs: `webmachine_logger` and `webmachine_perf_logger`, for example, though I was implementing a custom logger for another project when I found this issue.  This logger is called from [webmachine_decision_core:respond/1](https://github.com/basho/webmachine/blob/master/src/webmachine_decision_core.erl#L98) and [webmachine_mochiweb:handle_error/3](https://github.com/basho/webmachine/blob/master/src/webmachine_mochiweb.erl#L109).

**Comment by beerriot** [comment]
This seems to still be the case in today's Webmachine (ace95e0f from my fork merging develop into master). Instead of using `logdis_logger` and the `application:set_env` call, do this:

1. Build `logdis_resource` into an app, and place it in the dispatch list, start the app in "console" mode.
2. Run `webmachine_log:add_handler(webmachine_access_log_handler, ["log"]).` in the console.
3. `tail -F` the file that the logger tells you it's logging to
4. `curl` the path you set for the `logdis_resource`

If you wait until curl shows you all 11 a's, you will also see a log line appear in your log tail.

If you ^C curl before the ten seconds it takes to produce the body, you will never see a log line appear.

**Comment by seancribbs** [comment]
> If you ^C curl before the ten seconds it takes to produce the body, you will never see a log line appear.

Interestingly, `nginx` when in a reverse-proxy setup will log a `499` status if the client disconnects early, because it can't know for certain what the response was!

I suspect here we have an issue of not reaching `finish_response` in the resource (and hence the call to `do_log`), and possibly the process spawned from mochiweb for the request getting terminated when the TCP socket is shutdown (are they linked? is it a `badmatch` on the result of `gen_tcp:send`?).

I wonder if we could debug the problem by adding supervision in a few places where it doesn't exist and letting OTP report on the crash reasons.

**Comment by beerriot** [comment]
> letting OTP report on the crash reasons.

This sounds like another good reason to update our mochiweb deps. [The release notes for v3.0.0](https://github.com/mochi/mochiweb/releases) talk about changing exit reasons from `normal` to `{shutdown, Error}`. Those `normal` exits [were noted as problems elsewhere](https://github.com/webmachine/webmachine/issues/290#issuecomment-378780341) too.
