### ISSUE TITLE
post_is_create/2 and create_path/2 Causes IP address reversal

### ISSUE THREAD

**Issue by greyson** [webmachine/webmachine#71]
I ran the resource I defined in https://gist.github.com/2631569 and received an incorrect location header:

```
http://1.0.0.127:8000/prob/TestDevice
```

Instead of the correct

```
http://127.0.0.1:8000/prob/TestDevice
```

I am using WebMachine 1.9.0 (someone had painted it blue)

**Comment by kellymclaughlin** [comment]
Fixed by [this](https://github.com/basho/webmachine/commit/6b987382dad8fe96af6f0287a20450b7fef54411) commit.
