### ISSUE TITLE
inets not started

### ISSUE THREAD

**Issue by voila** [webmachine/webmachine#78]
With Erlang R15B (erts-5.9), when I try to start the demo app, I get :

{"init terminating in do_boot",{{case_clause,{error,{not_started,inets}}},[{webmachine_demo,ensure_started,1,[{file,"src/webmachine_demo.erl"},{line,7}]},{webmachine_demo,start,0,[{file,"src/webmachine_demo.erl"},{line,28}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

adding ensure_started(inets) in webmachine_demo.erl does the trick

**Comment by kellymclaughlin** [comment]
This has been addressed in `master`. Thanks for reporting the issue.
