### ISSUE TITLE
many ssl certs fail to work

### ISSUE THREAD

**Issue by mrdrmmn** [webmachine/webmachine#79]
ssl support does not appear to be fully functional.  some valid cert/key pairs simply do not work.

The following command will generate a self-signed certificate that does not work with riak, but works with every other piece of software I have tried it with:

openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/riak/ssl.key -out /etc/riak/ssl.crt

This is what in the logs when attempting to connect to the https interface using the cert/key pair generated using the command above:

[root@riak01 riak]# curl -k -vvv
https://127.0.0.1:8092/riak/__riak_client_test__
- About to connect() to 127.0.0.1 port 8092 (#0)
-   Trying 127.0.0.1... connected
- Connected to 127.0.0.1 (127.0.0.1) port 8092 (#0)
- Initializing NSS with certpath: sql:/etc/pki/nssdb
- warning: ignoring value of ssl.verifyhost
- NSS error -5938
- Closing connection #0
- SSL connect error
  curl: (35) SSL connect error

And I see the following in the logs:

console.log:
2012-07-13 11:05:52.023 [error] <0.5313.0> CRASH REPORT Process <0.5313.0>
with 0 neighbours crashed with reason:
{ekeyfile,[{gen_fsm,init_it,6},{proc_lib,init_p_do_apply,3}]}
2012-07-13 11:05:52.026 [error] <0.134.0> Supervisor ssl_connection_sup had
child undefined started with {ssl_connection,start_link,undefined} at
<0.5313.0> exit with reason ekeyfile in context child_terminated
2012-07-13 11:05:52.031 [error] <0.139.0> application: mochiweb, "Accept
failed error", "{error,ekeyfile}"
2012-07-13 11:05:52.033 [error] <0.139.0> CRASH REPORT Process <0.139.0>
with 0 neighbours crashed with reason: {error,accept_failed}
2012-07-13 11:05:52.035 [error] <0.135.0>
{mochiweb_socket_server,310,{acceptor_error,{error,accept_failed}}}

crash.log:
2012-07-13 11:05:52 =ERROR REPORT====
[83,83,76,58,32,"1112",58,32,"error",58,"[]",32,"/etc/riak/ssl.key","\n",32,32,[91,[[123,["ssl_connection",44,"init_private_key",44,"5"],125],44,10,"
  ",[123,["ssl_connection",44,"ssl_init",44,"2"],125],44,10,"
",[123,["ssl_connection",44,"init",44,"1"],125],44,10,"
",[123,["gen_fsm",44,"init_it",44,"6"],125],44,10,"
",[123,["proc_lib",44,"init_p_do_apply",44,"3"],125]],93],"\n"]2012-07-13
11:05:52 =CRASH REPORT====
  crasher:
    initial call: ssl_connection:init/1
    pid: <0.5313.0>
    registered_name: []
    exception exit: ekeyfile
      in function  gen_fsm:init_it/6
      in call from proc_lib:init_p_do_apply/3
    ancestors: [ssl_connection_sup,ssl_sup,<0.130.0>]
    messages: []
    links: [<0.134.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1597
    stack_size: 24
    reductions: 1185
  neighbours:
2012-07-13 11:05:52 =SUPERVISOR REPORT====
     Supervisor: {local,ssl_connection_sup}
     Context:    child_terminated
     Reason:     ekeyfile
     Offender:
[{pid,<0.5313.0>},{name,undefined},{mfargs,{ssl_connection,start_link,undefined}},{restart_type,temporary},{shutdown,4000},{child_type,worker}]

2012-07-13 11:05:52 =ERROR REPORT====
[{application,mochiweb},"Accept failed error","{error,ekeyfile}"]2012-07-13
11:05:52 =CRASH REPORT====
  crasher:
    initial call: mochiweb_acceptor:init/3
    pid: <0.139.0>
    registered_name: []
    exception exit: {error,accept_failed}
      in function  mochiweb_acceptor:init/3
      in call from proc_lib:init_p_do_apply/3
    ancestors: ['https_0.0.0.0:8092',riak_core_sup,<0.88.0>]
    messages: []
    links: [<0.135.0>,#Port<0.5661>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 233
    stack_size: 24
    reductions: 818
  neighbours:
2012-07-13 11:05:52 =ERROR REPORT====
{mochiweb_socket_server,310,{acceptor_error,{error,accept_failed}}}

erlang.log.1 and error.log (which are identical):
11:05:52.018 [error] SSL: 1112: error:[] /etc/riak/ssl.key
  [{ssl_connection,init_private_key,5},
   {ssl_connection,ssl_init,2},
   {ssl_connection,init,1},
   {gen_fsm,init_it,6},
   {proc_lib,init_p_do_apply,3}]

11:05:52.023 [error] CRASH REPORT Process <0.5313.0> with 0 neighbours
crashed with reason:
{ekeyfile,[{gen_fsm,init_it,6},{proc_lib,init_p_do_apply,3}]}
11:05:52.026 [error] Supervisor ssl_connection_sup had child undefined
started with {ssl_connection,start_link,undefined} at <0.5313.0> exit with
reason ekeyfile in context child_terminated
11:05:52.031 [error] application: mochiweb, "Accept failed error",
"{error,ekeyfile}"
11:05:52.033 [error] CRASH REPORT Process <0.139.0> with 0 neighbours
crashed with reason: {error,accept_failed}
11:05:52.035 [error]
{mochiweb_socket_server,310,{acceptor_error,{error,accept_failed}}}

If this was only a problem with self-signed certificates generated in this manner, I would not be filing this as a bug.  However, I am seeing the same behavior with some valid signed certificates as well.

Here is a link to the mailing list thread which contains additional inofrmation:

http://www.mail-archive.com/riak-users@lists.basho.com/msg07923.html

**Comment by mrdrmmn** [comment]
It is likely that I may have associated this with the wrong repo.  I was thinking mochiweb and webmachine were the same thing.  Not one hundred percent sure where this should go as this appears to likely be a problem with the version of the erlang ssl libraries or possibly mochiweb which also is not written by basho.  If I was more familiar with erlang I would attempt to write a piece of code to test this directly.  Any thoughts?  This may prevent us from using riak as it seem likely it won't work with the (paid addon for) multi-data center replication over ssl which seem very problematic.

If I am simply doing something wrong, please let me know, but I was not able to find anyone on the mailing list who had any ideas.

**Comment by cmeiklejohn** [comment]
@therevmj I've generated a certificate and key file using the openssl command above, but attempting to manually start SSL from the erlang console and using the certificate in Riak both seem to work fine for me.  Can you provide more information regarding the environment which you are running Riak on (Erlang version, Riak package number, OS).  

Also, feel free to hit me up on IRC in #riak.

**Comment by mrdrmmn** [comment]
Interesting.  Here are the details on the setup I am using:

[root@riak01 ~]# cat /etc/redhat-release 
CentOS release 6.3 (Final)

[root@riak01 ~]# rpm -qi riak
Name        : riak                         Relocations: (not relocatable)
Version     : 1.1.4                             Vendor: Basho Technologies
Release     : 1.el6                         Build Date: Tue 19 Jun 2012 11:49:00 AM PDT
Install Date: Thu 12 Jul 2012 02:02:45 PM PDT      Build Host: build-centos-6-64.den.basho
Group       : Development/Libraries         Source RPM: riak-1.1.4-1.el6.src.rpm
Size        : 36798101                         License: Apache License
Signature   : (none)
Packager    : Basho Technologies riak-user@lists.basho.com
URL         : http://basho.com
Summary     : Riak Distributed Data Store
Description :

[root@riak01 ~]# /usr/lib64/riak/erts-5.8.5/bin/erl -version
Erlang (ASYNC_THREADS,HIPE) (BEAM) emulator version 5.8.5

As I am sure you noticed, this is the erlang provided by the riak packages.

I ran a test with the erlang provided by the riak package and also with the erlang provided by CentOS 6.3 and I am seeing the exact same behavior.  Here is the how I set up the server side and the output when I tried to connect:

[root@riak01 ~]# erl
Erlang R14B04 (erts-5.8.5) [source] [64-bit] [rq:1] [async-threads:0] [kernel-poll:false]

Eshell V5.8.5  (abort with ^G)
1> ssl:start(). {ok, ListenSocket} = ssl:listen(9999, [{certfile, "/etc/riak/ssl.crt"}, {keyfile, "/etc/riak/ssl.key"},{reuseaddr, true}]). {ok, Socket} = ssl:transport_accept(ListenSocket).
ok
2> {ok, ListenSocket} = ssl:listen(9999, [{certfile, "/etc/riak/ssl.crt"}, {keyfile, "/etc/riak/ssl.key"},{reuseaddr, true}]). {ok, Socket} = ssl:transport_accept(ListenSocket).
{ok,{sslsocket,new_ssl,
               {#Port<0.911>,
                {config,{ssl_options,[],verify_none,
                                     {#Fun<ssl.1.24582685>,[]},
                                     false,false,undefined,1,"/etc/riak/ssl.crt",undefined,
                                     "/etc/riak/ssl.key",undefined,[],undefined,[],undefined,
                                     undefined,
                                     [<<0,...>>,<<...>>|...],
                                     #Fun<ssl.0.123982462>,true,...},
                        [{reuseaddr,true}],
                        {socket_options,list,0,0,0,true},
                        [{reuseaddr,true},
                         {packet_size,0},
                         {packet,0},
                         {header,0},
                         {active,false},
                         {mode,binary}],
                        {gen_tcp,tcp,tcp_closed,tcp_error}}}}}
3> {ok, Socket} = ssl:transport_accept(ListenSocket).

=ERROR REPORT==== 25-Jul-2012::12:56:27 ===
SSL: 1112: error:[] /etc/riak/ssl.key
  [{ssl_connection,init_private_key,5},
   {ssl_connection,ssl_init,2},
   {ssl_connection,init,1},
   {gen_fsm,init_it,6},
   {proc_lib,init_p_do_apply,3}]

*\* exception exit: {badmatch,{error,ekeyfile}}

I suppose this is looking like a problem with the erlang version or the ssl libraries under centos 6.  Let me know what you find.  Thanks.

**Comment by cmeiklejohn** [comment]
Sounds good, I'm going to build a CentOS 6.3 VM to try it out.

**Comment by cmeiklejohn** [comment]
Well, good news.  I can reproduce the problem on my CentOS 6.3 VM.  Let me debug this and get back to you.

**Comment by mrdrmmn** [comment]
I've done a bit more testing myself, and the problem does not occur on CentOS 5.8 using the same riak and erlang versions.  Not sure how helpful that is, but it is another data point.  I would say this is a bug in the openssl libraries in CentOS 6.3, however on the same server, I can fire up an instance of nginx utilizing the exact same certificate and key and it works perfectly fine.  Perhaps something about the way CentOS 6.3 and Basho compile and link the erlang binaries?

**Comment by cmeiklejohn** [comment]
@therevmj Do you mind pulling Riak from github and building with the CentOS 6.3 packages and trying that so we can rule out the bundled erts?

**Comment by mrdrmmn** [comment]
I'm confident we can rule out the bundled erts as the direct cause of the problem as I tested using erl on the command line both with the erl provided by the riak packages and the erl provided by the centos 6.3 packages.  But i can pull riak fom github and give it a try.  I suppose the next thing to try (assuming this still has the same problem) will be build erlang from source, and then finally build openssl from source and compile erlang against the new openssl and then riak against the new erlang.  This will take me a bit of time, but I will get it going and report back.

**Comment by mrdrmmn** [comment]
While I was in the process of building things from source, I decided to take another route which I believe gets us to the same place.

I swapped the generated certificates between the working centos5 machine and the broken centos6 machine and immediately the error occured on the centos5 machine and went away on the centos6 machine.  This would initially seem to indicate that there is a problem with the certificates generated on centos6.  However, the certificates that fail under riak, work under nginx so this is not the problem, but clearly there is something different about the certificates generated on centos6.  I did some poking and found the following difference in the text dump of the "good" and "bad" certificates:

In the "good" certificate, the 'X509v3 Authority Key Identifier' contains only as 'keyid' field.  In the "bad" certificate, it also contains a 'DirName' and 'serial' field.

I copied /etc/pki/tls/openssl.cnf from the centos6 machine to the centos5 machine and generated a new certificate.  It worked fine, and upon inspection, I saw that the newly generated certificate is missing the 'DirName' and 'serial' from the 'X509v3 Authority Key Identifier' section.  This tells us that this is something hard coded into openssl to be added by default under centos6 and not under centos5.  There may be a way to toggle this, but we are already well past my real understanding of ssl.

Ultimately, this seems pretty clear that it is a problem in the way erlang handles certificates and it seems to be related to the extra fields in the 'X509v3 Authority Key Identifier' section.

**Comment by mrdrmmn** [comment]
I've backtracked through the erlang code that handles ssl connections to pubkey_pem:decode_key so far and I believe that (or something beyond it is where the problem occurs.  I'm going to build the most recent erlang which has improved ssl handling and test it directly.  If the problem still occurs, then I suppose this falls to the erlang folks.  I'll keep this open for a bit yet and update it with my findings on the erlang side of things.  Out of curiosity, is there a particular reason you don't use a newer version of erlang in the binary packages?  If not and the current version fixes this problem, it would be very resonable to re-package things with the current version.

**Comment by mrdrmmn** [comment]
Ok, so erlang R15B01 does indeed fix this problem.  This should be documented somewhere riak realted probably and the basho provided binaries should probably be built to include a newer erlang if at all possible.  Should I open this as a bug in a different location and close this bug, or should I leave it here?

**Comment by cmeiklejohn** [comment]
@therevmj thanks for being so detailed in your debugging.  At this point, we're close to releasing the 1.2 release of Riak, which is bundled with R15B01, and waiting for that might be your best bet.

**Comment by mrdrmmn** [comment]
Seems reasonable.  We are still in early development for the project that will be using riak and ssl is not critical right now, but it will be later on.  Worst case, I can always build my own packages for riak and erlang as we now know that would solve this problem.  I'll mark this as closed.
