### ISSUE TITLE
Invalid connection header comparisons disables server connection close

### ISSUE THREAD

**Issue by defunerik** [webmachine/webmachine#80]
I just discovered a flaw in the mochiweb code that checks a the request header's Connection field to determine whether it should close the connection to the client after sending the response. The effect is that the server will not terminate the connection when a Connection:Close header field is sent unless the value of the Connection field is, literally, "close", all lower case. The Connection header field value is specified as case insensitive, and at least one client (not a web browser, but a monitoring device) sets the value to "Close". This particular client also expects the server to close the connection  after sending the response, and fails to process the response unless this is so. It should be possible as well for the client to close the connection after successfully receiving the entire response, but the client is embedded in a device, and firmware updates are months in the making, if it is even reasonably fixable.

In order to get this client to work with webmachine I found two separate hacks. I couldn't figure out how to have webmachine indicate that the server connection should close at the end of the transaction. The first requires no changes to webmachine or mochiweb -- it is to set a value in the process dictionary, like so:

```
put(mochiweb_request_force_close, true)
```

This code goes into my webmachine handler. This is an internal implementation detail of mochiweb, and not at all pretty.

The second is to make the fix to mochiweb, in the mochiweb_request module. I've made private changes to fix the code. I guess the  proper thing would be to branch off mochiweb for these changes, and the try to make then good enough to fold back into mochiweb proper. Don't have time now.

I am reporting it here since webmachine relies on mochiweb handling the connection part of the http protocol. 

Of course, mochiweb should fix this, but in the mean time it might be possible to have webmachine do something like inspect the request headers itself, and enforce the behavior by using the process dictionary hack. I would only suggest this because webmachine relies on mochiweb to handle certain aspects of the http protocol, and if it is discovered that there is a flaw, and it can be fixed prior to mochiweb being updated, then perhaps it should be.

Thanks.

**Comment by beerriot** [comment]
Looks like mochiweb merged your fix in v2.3.2 (mochi/mochiweb#81), and webmachine now uses v2.22.0, so this is probably fixed. Thanks!
