### ISSUE TITLE
parse_qs and strings

### ISSUE THREAD

**Issue by defunerik** [webmachine/webmachine#84]
Are the keys and values in query string and friends supposed to be strings?

webmachine offers wrq:get_qs_value and wrq:get_qs for getting at url query strings, and we otherwise need to use mochiweb_util:parse_qs directly on the request body if we want to get at the application/x-www-form-urlencoded body of a POST. 

On the part of webmachine, the result of get_qs (which uses mochiweb's parse_qs under the hood) is documented to be a proplist where the keys and values are strings. Strings are defined by webmachine to be "a list() with all elements in the ASCII range".

I have a few points to make:
1. Isn't it confusing to use a string definition that is different from Erlang?
2. This definition does not match what mochiweb produces from parse_qs
3. Mochiweb produces a proplist where the keys and values are byte lists.
4. Note that the bytes are full 8 bit bytes, not 7 bit ASCII. Note that the query string keys and values will have been decoded from possible %XX hex encoding, so whereas the original encoded querystring is ASCII, the decoded data is not.
5. The bytes should be interpreted in the modern era as representing utf8.
6. The natural representation of utf8 bytes these days is binary.
7. mochiweb, at least the current incarnation, is unlikely to change the representation of of parse_qs.
8. I see the the correct handling to produce binaries and/or Erlang unicode strings (decoded from utf8).
9. If you try to use the results of wrq:get_qs_value as strings you will likely at some point get corrupt strings,  because a single multi-byte utf8 character will become mulitple Erlang integer characters.
10. Despite the confusion, the workaround is simple. Use list_to_binary on the result of wrq:get_qs_value, because this will stuff the bytes into a binary, which, although the default interpretation is utf8, can be decoded with the unicode module to produce real Erlang strings, or used directly with apis like json, etc.

Please set me on my way if I'm out of line.

Erik.

**Comment by beerriot** [comment]
This issue was primarily about the documentation at https://github.com/webmachine/webmachine/wiki/Request-Data-API

I've updated the `string()` type description on that page. It has always been a list of bytes, and not strictly ASCII, but this is a common mistake to make.

Binary representation may be a good representation in the future, but we'll likely follow what mochiweb does, to avoid unnecessary list-binary conversion.
